### ISSUE TITLE
compare java libraries

### ISSUE THREAD

**Issue by jedahan** [buglabs/bugswarm-js#10]
write which works well with what

**Comment by barberdt** [comment]
Afaik, the only completed java library in use atm is the client library located in the bugswarm-connector project that was written by @kgilmer. @jconnolly and myself have been doing some work with it. What other library is there to compare to?

**Comment by jconnolly** [comment]
I wrote one that I've abandoned in favor of Ken's.

**Comment by jconnolly** [comment]
it's here, https://github.com/buglabs/bugswarm-api/tree/jconnolly-http-api/java/com.buglabs.bugswarm.api

I abandoned it because we were utilizing a similar implementation, but Ken's JSON and error handling was much further along than mine.

**Comment by barberdt** [comment]
So shall we conclude the comparison as supporting ken's and move on to refining it and fine-tuning its features? @jedahan, @jconnolly?

**Comment by c4milo** [comment]
hey just curious, if an user only wants to participate in a swarm, he only need the jar for that part of the API?

**Comment by jconnolly** [comment]
It's all rolled into one at the moment, Camilo.  The configuration and participation API and implementation are part of the same package, and jar.

**Comment by barberdt** [comment]
Motion for le close.

**Comment by jconnolly** [comment]
Yea

**Comment by kgilmer** [comment]
I can produce separate jars with each API isolated if that's desired.  Just LMK.
