### ISSUE TITLE
Remove 'java' directory until @kgilmer's library is ready to be moved over here

### ISSUE THREAD

**Issue by barberdt** [buglabs/bugswarm-js#11]
Motion for this to happen to reduce confusion on our side as well as among outside devs. Thoughts?

**Comment by jconnolly** [comment]
From master?

**Comment by barberdt** [comment]
Aye. I guess this also pertains to the other non-existent libraries (ruby, etc...). We do point devs to this repo from the dev portal, so it makes sense to me.

**Comment by jconnolly** [comment]
Done!  https://github.com/buglabs/bugswarm-api/commit/2ac1af488d52b18bdcd131c43e8af3fe1b20ad97

**Comment by kgilmer** [comment]
Uh...you want me to move swarm.client to bugswarm-api repo?

**Comment by jconnolly** [comment]
Let's worry about it when the connector is finished.  But yes, ideally the API will be available here, separate from connector's implementation on top of it.

**Comment by jconnolly** [comment]
I look for a reason to blame your code for x,y,z and yet again I realize you're a Jedi knight.  

It's a small thing, but hi5 on choosing a Map<String, ?> for payload.  I now  understand generics, dynamic and static typing much, much more clearly.

A little token of gratitude,

John

**Comment by kgilmer** [comment]
Awesome, thanks for the gratitude!
