### ISSUE TITLE
Correlation Between CDN and Github

### ISSUE THREAD

**Issue by theterg** [buglabs/bugswarm-js#13]
Attempting to get started using the javascript library, i'm not seeing a correlation between the code in github and the code hosted on the CDN.  It would be useful for these to be linked, so that we can update the example code and keep it up to date with the library.
@aturley @santiago

**Comment by c4milo** [comment]
there is not correlation @theterg since the CDN version is a distributable and optimized version for browser consumption.  Meaning that it's also merged with its dependencies and minimized. The example code should use CDN versions. Please let me know if I misunderstood the issue.

**Comment by c4milo** [comment]
@theterg ping

**Comment by theterg** [comment]
Ok.  Maybe a list of valid CDN libraries would be helpful - i'm not certain if this exists already.

**Comment by c4milo** [comment]
- Production
  http://cdn.buglabs.net/swarm/swarm-v0.3.2.js
  http://cdn.buglabs.net/swarm/swarm-v0.3.2.min.js
- Testing
  http://cdn.buglabs.net/swarm/test/swarm-v0.3.2.js
  http://cdn.buglabs.net/swarm/test/swarm-v0.3.2.min.js
- Development
  http://cdn.buglabs.net/swarm/dev/swarm-v0.3.2.js
  http://cdn.buglabs.net/swarm/dev/swarm-v0.3.2.min.js

That's it. Public users should use only production links.
