### ISSUE TITLE
Reorganize bugswarm-api

### ISSUE THREAD

**Issue by jedahan** [buglabs/bugswarm-js#5]
Other services split each api by language/platform.

I suggest we do the same. Argue why its a bad idea.

**Comment by aturley** [comment]
We do it the way PubNub does it:
https://github.com/pubnub/pubnub-api

Pusher does it differently:
http://pusher.com/docs/rest_libraries

**Comment by jedahan** [comment]
By decoupling we:
- increase visibility and legitimacy of third-party libraries
- let package managers integrate more easily
- allow for multiple libraries per-language

**Comment by c4milo** [comment]
the api is already split by language, what do you mean by platform? is it really necessary?

**Comment by jedahan** [comment]
@c4milo, see https://github.com/buglabs/bugswarm-api/issues/5#issuecomment-2289568

**Comment by barberdt** [comment]
What's the reasoning for wanting multiple libraries of the same api for a given language?

**Comment by jedahan** [comment]
Multiple people code in different ways. Some don't like the semantics of a particular library or its features/bugs and write their own. Some people want integration in their favorite framework while others want an SQL-like language.

see http://www.mongodb.org/display/DOCS/Drivers , http://pusher.com/docs/rest_libraries

**Comment by barberdt** [comment]
Aren't all of these libraries required to have the same semantics (join, send, leave)?

**Comment by jedahan** [comment]
Most definitely not! Look at a few of the examples I posted.

**Comment by barberdt** [comment]
@c4milo, please clarify. The BUGswarm API set of libraries was designated to libraries that abstracted the http streaming API (with the inclusion of the javascript library as well) and followed a strict form of implementing the 'join', 'send', 'leave', and callback (for consuming) methods. Correct?

**Comment by c4milo** [comment]
@barberdt yes, we should keep a similar contract or usage across libraries that we **support**. @jedahan I still don't see a concret need to split out libraries by platform, but I do see a real need of implementing more libraries or improving existent libraries. Regarding third-party contributions I'd say let's link them in some page but not have repositories for them. It's only my humble opinion.

**Comment by jedahan** [comment]
This has diverged into a discussion about library design, which should be split off as another issue since there is work to be done in that field.

I still see three reasons to split the libraries, and zero reasons not to.

@aturley has informed us that this is good enough for the developer preview, so I will save my elaborations until after the 11th
